src/objects/Damage_Report__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Damage Report</label>
    <nameField>
        <displayFormat>D{000000}</displayFormat>
        <label>Report Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Damage Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MyDemoClass.cls
public class MyDemoClass{
    
    Damage_Report__c dr = new Damage_Report__c(Description__c='this is a damage report');
    
    public static void fixLineItems(List<Line_Item__c> lis){
        List<Line_Item__c> liToWorkWith = new List<Line_Item__c>();
    
    	for (Line_Item__c li: lis){
        
            if (li.Quantity__c < 1){
                li.Quantity__c = 1; 
                liToWorkWith.add(li);     
            }
        
        }
    	Database.update(liToWorkWith); 
        
    }

}